### ISSUE TITLE
IVCT-VRF-Encoding tests: improve result reporting

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#130]
Attached the last part of the console output of the encoding tests against VR-Forces, now also with spatial data.

To determine what is wrong better result reporting is necessary.

[IVCT-VRF-Encoding-1.txt](https://github.com/MSG134/IVCT_Framework/files/2168141/IVCT-VRF-Encoding-1.txt)

**Comment by ducana** [comment]
Added more details of names, handles and hex dump of buffer to help find the error.

**Comment by bergtwvd** [comment]
Agree to wait on an IVCT version where the TC param values can be set via env variables. This makes it much more easy to run these tests.

**Comment by ducana** [comment]
There seems to be a misunderstanding here: no plan exists to change all the TCparam values to env variables. There was a proposal to look into having some values such as RTI host address or federation name as env variables. The other TCparam values typically vary for each badge (and maybe test case) for each SUT. To manage these values for a large number of badges, test cases and SUTs as env variables is not easy. Are there ideas how that would work?

**Comment by ducana** [comment]
Added current position in byte buffer where the error is detected. The position uses the Java/C++ standard where the buffer starts at position 0 (zero). Changed buffer analysis code to throw exceptions rather than use return values, since the return values were not checked in every case. Java compiler warns about not catching exceptions.
