### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jaffguo** [MSG134/IVCT_Framework#26]
Questions:
Question#1
I used the following steps to run the TC0001:
Step1: run "activemq start" in a command prompt
Step2: add TS_HelloWorld-0.0.1.jar and its absolute path to TC.bat's "CLASSPATH" var
Step3: run "TC JMSTestRunner" in another command prompt
Step4: login http://localhost:8161/admin
Step5: click "Queues"
Step6: click "Send To"
Step7: type "de.fraunhof.iosb.tc_helloworld.TC0001" to the Message Body area
    to replace the previous test
Step8: click "Send" button
The result is as follows:
In the "activemq start" command prompt", message displayed: "INFO : Connector vm://localhost started"
In the "TC JMSTestRunner" command prompt, an Exception is displayed:
   Could not instantiate de.fraunhof.iosb.tc_helloworld.TC0001
   java.lang.ClassNotFoundException: de.fraunhof.iosb.tc_helloworld.TC0001
My question#1: "Are the steps above correct?" If not, what are a correct step sequence?
            If yes, any ideas for potential causes?

Question#2:
I used a FREE Pitch RTI jar file "prti1516e.jar"(downloaded a month ago and 
running only with Java 1.6) to replace the IEEE1516e-0.1.0.jar (in TS_HolloWrold.bat and in lib) 
and tried to run de.fraunhof.iosb.tc_helloworld.TC0001 in a windows command prompt 
without "activemq start", without "TC JMSRunner", and without a http://localhost:8161/admin 
browser. I got the following Exception:
hla.rit1516e.exception.RTIinternalError: Cannot find factory
    at hla.rti1516e.RtiFactoryFactory.getRtiFactory(RtiFactoryFactory.java:48)
    at de.fraunhofer.iosb.tc_lib.IVCT_RTI_Factctory.getIVCT_RTI(IVCT_Factory.java:39)
       ...
My question#2: Could the IEEE1516e-0.1.0.jar be replaced by the Free PitchRTI prti1516e.jar 
    with java 1.6? Would the way above to the run the TC0001 be correct? If TC0001 can be run in 
     this way, what may be the causes of the exception?
Thanks,

**Comment by jaffguo** [comment]
The "running only with Java 1.6" issue in the Question#2 was solved, and it may run with Java 1.8 now. The main issue in Question#2 should be "how to replace the IEEE1516e-0.1.0.jar with the prti1516e.jar to run TC0001?"

**Comment by ducana** [comment]
When I look at your steps in Question#1, I see a few old commands which no longer apply. Last week I sent out instructions for the new version (incompatible with the old one):
--------------------------------------------------------------------------------------------------------------------
Good morning,

The new IVCT Command Line Tool is available from the GitHub at:

https://github.com/MSG134/IVCT_Framework   
https://github.com/MSG134/TS_HelloWorld

on the development branch.

Please download the sources from both locations and generate the executables via the Gradle commands as described in the https://github.com/MSG134/IVCT_Framework/wiki/gradleDoc.

Only TS_HelloWorld contains runnable test cases, these have to be installed by copying:

TS_HelloWorld\bin\de\fraunhofer\iosb\tc_helloworld   to  IVCT_Framework\TC\bin\de\fraunhofer\iosb\tc_helloworld
TS_HelloWorld\TS_HelloWorld\bin\de\fraunhofer\iosb\tc_lib_helloworld   to   IVCT_Framework\TC\bin\de\fraunhofer\iosb\tc_lib_helloworld

In the future, it is expected that a Gradle command can perform the above task.

The documentation on the IVCT Command Line Tool is available at:

https://github.com/MSG134/IVCT_Framework/wiki/commandlinetool

An example of the Test Suite structure and the SUT structure as shown in the WebEx on the 16th of March can be found in the attached Demo.zip. 

A number of configuration adjustments (e.g. the global variable IVCT_HOME has to be set) have to be made in order to use the tool. These are described in the README.txt in Demo.zip.

Please contact me if you have any questions or suggestions.

Regards,

John Mulder
--------------------------------------------------------------------------------------------------------------------

I can send you the Demo.zip (8k) file if you send me an email address.

**Comment by rhzg** [comment]
refering to question#2 there is a section in the wiki pages  

- https://github.com/MSG134/IVCT_Framework/wiki/3rdpartyRti

saying a few things about that issue

**Comment by rhzg** [comment]
problem solved
