### ISSUE TITLE
Configuring ActiveMQ host/port via environment variables

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#60]
Currently, the ActiveMQ host/port are configured via a properties file (or XML config file for logback).

For containerization of the IVCT it would be preferable to configure this via Environment variables. This allows starting a containerized IVCT and to connect it to different ActiveMQ hosts without rebuilding the image.

**Comment by rhzg** [comment]
Like issue #61 we will most likely require more flexibility for our tool configuration that the key/value concept of environment variables. Either because we need nested structures (like the capability badges) or because we use external tools with a given configuration mechanism (like logback). 

What about mapping config files from the host OS directly into a docker image? That would also be useful for our runtime data where we create the log files and where we configure the systems under tests. I believe it makes sense to separate such production specific configurations from the executable images and from the developer specific images.

**Comment by PHameete** [comment]
Hi Reinhard, 

I've posted my two cents at #60. I think these issues can be generalized into a more general issue: "How can we make dynamic (at runtime) configuration of the IVCT and its test suites possible and as easy as we can?".
