### ISSUE TITLE
Building the IEEE1516 module with OpenJDK 8+ provides errors when generating Javadoc

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#63]
Building the IEEE1516 module using 'gradlew install' and OpenJDK 8 or higher results in the following errors when generating the Javadoc:

/usr/local/IVCT_Framework/IEEE1516e/src/main/java/hla/rti1516e/encoding/ByteWrapper.java:144: error: unknown tag: noinsp
ection
    * @noinspection PointlessBitwiseExpression
      ^
/usr/local/IVCT_Framework/IEEE1516e/src/main/java/hla/rti1516e/encoding/ByteWrapper.java:194: error: unknown tag: noinsp
ection
    * @noinspection PointlessBitwiseExpression
      ^
/usr/local/IVCT_Framework/IEEE1516e/src/main/java/hla/rti1516e/encoding/DataElementFactory.java:14: error: self-closing
element not allowed
 * <p/>
   ^
3 errors

**Comment by rhzg** [comment]
The IEEE module is contains the API files from the standard. I guess to solve that issue we need to wait for the next iteration of the HLA standard (LHA 4.0 is in preparation)

**Comment by PHameete** [comment]
Thanks! Do you know if there's a place where I can inform the developers of the standard of this so they may be able to include it in the next release?

Fortuntaly, this does not break the build by the way because you configured Javadoc errors not to cause failure :-). Perhaps we can add a gradle command to build a distribution without src and javadoc as that won't be needed for some environments.

**Comment by rhzg** [comment]
I guess Tom van den Berg tom.vandenberg@tno.nl<mailto:tom.vandenberg@tno.nl> would be a good point of contact for you to talk about HLA standard issues.

Von: PHameete [mailto:notifications@github.com]
Gesendet: Montag, 12. Juni 2017 11:55
An: MSG134/IVCT_Framework <IVCT_Framework@noreply.github.com>
Cc: Herzog, Reinhard <reinhard.herzog@iosb.fraunhofer.de>; Comment <comment@noreply.github.com>
Betreff: Re: [MSG134/IVCT_Framework] Building the IEEE1516 module with OpenJDK 8+ provides errors when generating Javadoc (#63)


Thanks! Do you know if there's a place where I can inform the developers of the standard of this so they may be able to include it in the next release?

Fortuntaly, this does not break the build by the way because you configured Javadoc errors not to cause failure :-). Perhaps we can add a gradle command to build a distribution without src and javadoc as that won't be needed for some environments.

**Comment by rhzg** [comment]
This issue will need to be considered along with the next HLA standard release.
